version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: ita
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-service
    restart: always
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # Web UI

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:123123@db:5432/ita
      JWT_SECRET: your_jwt_secret_here
      PORT: 3000

  reservation-service:
    build:
      context: ./reservation-service
    container_name: reservation-service
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8000:8000"
      - "50051:50051"
    environment:
      MONGO_URL: mongodb://mongo:27017/
      DATABASE_NAME: reservationdb
      GRPC_SERVER_PORT: 50051
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_QUEUE: reservation_notifications
    volumes:
      - ./reservation-service:/app

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      DATABASE_DSN: root:root@tcp(host.docker.internal:3306)/paymentdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
 


volumes:
  pgdata:
  mongo_data:
