version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: ita
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-service
    restart: always
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # Web UI

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./payment-service/creatingdb.sql:/docker-entrypoint-initdb.d/creatingdb.sql

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:123123@db:5432/ita
      JWT_SECRET: your_jwt_secret_here
      PORT: 3000

  reservation-service:
    build:
      context: ./reservation-service
    container_name: reservation-service
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8000:8000"
      - "50051:50051"
    environment:
      MONGO_URL: mongodb://mongo:27017/
      DATABASE_NAME: reservationdb
      GRPC_SERVER_PORT: 50051
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_QUEUE: reservation_notifications
    volumes:
      - ./reservation-service:/app

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      DATABASE_DSN: root:root@tcp(mysql-db:3306)/paymentdb?parseTime=true
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/



  gateway-web:
    build:
      context: ./gateway-web
    container_name: gateway-web
    depends_on:
      - user-service
      - reservation-service
      - payment-service
    ports:
      - "4000:4000"
    environment:
      PORT: 4000

  gateway-mobile:
    build:
      context: ./gateway-mobile
    container_name: gateway-mobile
    depends_on:
      - user-service
      - reservation-service
      - payment-service
    ports:
      - "5000:5000"


volumes:
  pgdata:
  mongo_data:
  mysql_data:
