version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:123123@db:5432/ita
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: ita
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
