name: Payment Service CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./payment-service  # Point to the folder with go.mod

      - name: Run Unit Tests
        run: go test ./tests/...
        working-directory: ./payment-service  # Same here